### PR TITLE
Add yaml string support

### PR DESCRIPTION
**Pull request by clearydude**
Feel free to take or leave this PR but I'm working with yaml-based open API specs and figured it was an easy add. 

Note: I copied the pattern and used `serde_yaml` as the footnote text but I think it (and maybe the json ones above it) should just read `yaml` (and `json`)

### CODE REVIEW

**Comment by juhaku** [comment]
Awesome. Yeah. been thinking to add it but not been high on the list since haven't had a need for that. 
Could you add short documentation to the `REAMDE.md` and `utoipa/lib.rs` under **Features** section?

**Comment by juhaku** [comment]
And true.. should read `json` and `yaml`. feel free to fix :)

**Comment by clearydude** [comment]
I'll add some documentation and update this PR (probably tomorrow). Thanks!!

**Review by juhaku — APPROVED** [review]
Sweet :candy:

**Pull request merged**
