### PR TITLE
utoipa-gen: Replace `assert-json-diff` with snapshot testing via `insta`

### PR DESCRIPTION
**Pull request by Turbo87**
This PR continues what https://github.com/juhaku/utoipa/pull/1247 has started by migrating all tests in `utoipa-gen` that use `assert-json-diff` to use `insta::assert_json_snapshot!()` instead.

Note that this PR currently includes https://github.com/juhaku/utoipa/pull/1252 to avoid conflicts from the `path_derive_auto_into_responses_actix` test suite.

### CODE REVIEW

**Review by juhaku — CHANGES_REQUESTED** [review]
Great work, thanks for putting the effort for migrating the tests :partying_face: 

Just missing the entry or CHANGELO.md under `Unreleased` title and `Changed` subtitle at the top of the file.

**Comment by Turbo87** [comment]
> Just missing the entry or CHANGELO.md under `Unreleased` title and `Changed` subtitle at the top of the file.

done :)

**Comment by Turbo87** [comment]
rebased on top of `master` now

**Review by juhaku — APPROVED** [review]
Good, let's get this show on the road. :rocket:

**Pull request merged**
