### PR TITLE
fix rocket-todo

### PR DESCRIPTION
**Pull request by miaobuao**

### CODE REVIEW

**Comment by juhaku** [comment]
What is actually broken in the rocket-todo example? As I tested in the master it does work quite well.

**Comment by miaobuao** [comment]
> What is actually broken in the rocket-todo example? As I tested in the master it does work quite well.

```
➤ cargo run
    Blocking waiting for file lock on build directory
   Compiling rocket-todo v0.1.0 (/home/meo/dev/github/utoipa/examples/rocket-todo)
error[E0599]: no variant or associated item named `Failure` found for enum `Outcome` in the current scope
   --> src/main.rs:130:34
    |
130 |                 None => Outcome::Failure((
    |                                  ^^^^^^^ variant or associated item not found in `Outcome<_, _, _>`

error[E0599]: no variant or associated item named `Failure` found for enum `Outcome` in the current scope
   --> src/main.rs:134:31
    |
134 |                 _ => Outcome::Failure((
    |                               ^^^^^^^ variant or associated item not found in `Outcome<_, _, _>`

error[E0308]: mismatched types
   --> src/main.rs:156:38
    |
156 |                     Outcome::Forward(())
    |                     ---------------- ^^ expected `Status`, found `()`
    |                     |
    |                     arguments to this enum variant are incorrect
    |
help: the type constructed contains `()` due to the type of the argument passed
   --> src/main.rs:156:21
    |
156 |                     Outcome::Forward(())
    |                     ^^^^^^^^^^^^^^^^^--^
    |                                      |
    |                                      this argument influences the type of `Outcome`
note: tuple variant defined here
   --> /home/meo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.0/src/outcome.rs:111:5
    |
111 |     Forward(F),
    |     ^^^^^^^

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `rocket-todo` (bin "rocket-todo") due to 3 previous errors
```

**Comment by juhaku** [comment]
I belive you have different version or rocket cached to your machine and somehow it uses that, the `rocket-todo` is actually and rocket support in general for rocket version `0.5.0-rc.3`. I bet the rocket has ever changed their API for the latest `0.5.0` version that is not taken in account in the rocket support of utoipa. If you run `cargo clean` and then `cargo run` I believe it start to work.

This PR should also update all the other modules in utoipa that are dependant of the `rocket` to the latest version of the rocket for to be complete.

**Comment by miaobuao** [comment]
image

I have run `cargo clean`, but the situation has not changed

**Comment by juhaku** [comment]
Yeah, as expected the thing is that you are running on `0.5.0` but the API is for `0.5.0-rc3` and between these releases the API has changed. There is now another PR that actually does this but also upgrades the rocket support for utoipa in general to the `0.5.0` from the previous `0.5.0-rc3`.

**Pull request closed without merging**
