### PR TITLE
Update to axum 0.6.0

### PR DESCRIPTION
**Pull request by davidpdrsn**
Resolves #345

### CODE REVIEW

**Review by juhaku — APPROVED** [review]
Super :+1:

**Comment by juhaku** [comment]
```

failures:

error: doctest failed, to rerun pass `-p utoipa-swagger-ui --doc`
---- src/lib.rs - (line 93) stdout ----
error[E0599]: the function or associated item `new` exists for struct `Router<B>`, but its trait bounds were not satisfied
  --> src/lib.rs:105:25
   |
15 |  let app = Router::<B>::new()
   |                         ^^^ function or associated item cannot be called on `Router<B>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `B: Clone`
           `B: Sync`
help: consider restricting the type parameters to satisfy the trait bounds
   |
13 |     B: HttpBody + Send + 'static, B: Clone, B: Sync
   |                                 ~~~~~~~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.

failures:
    src/lib.rs - (line 93)
```

**Comment by davidpdrsn** [comment]
@juhaku I believe it should be fixed. Wanna poke the CI button?

**Comment by juhaku** [comment]
Sure

**Pull request merged**
