### PR TITLE
Allow value_type serde_json::Value

### PR DESCRIPTION
**Pull request by jayvdb**
c.f. https://github.com/juhaku/utoipa/discussions/567

### CODE REVIEW

**Comment by juhaku** [comment]
I am wondering how does the any type is different to the virtual `Object` type? Moreover from the perspective of the client side code generation?

Originally the `Object` type standed for the purpose of rendering any json content that does not have a type. But sure the any type support could also be added.

Seems like the array representation of `type:` field is not valid OpenAPI specification.
image

I believe the any type should rather be rendered as presented here: https://swagger.io/docs/specification/data-models/data-types/. Look for `Any Type` bottom of the page.

Just wondering about the name `Value` that is it too generic? While it would match well with serde's `Value` it simultaneously may match with many other `Value` types that would be unexpected behavior. Just wondering whether it should be something more specific / unique? Like bluntly `AnyValue` or `AnyType` or `Anything`.

**Comment by jayvdb** [comment]
ok, yes, `type: [<all of the valid tyoes>]` is equivalent to not having any `type` at all.
But that is not what your image is showing.  it is saying it isnt happy with "null" being in the list, because `nullable: true" is another way of saying the same thing.
I am ambivalent with how we do `null`.  I can exclude it from the list, no problem.
*but* `object` is very different from `number`.  they are different, which is why `Value` is an enum with `Map` (which is `Object`) and `Number` as separate variants.

**Comment by juhaku** [comment]
image

**Comment by juhaku** [comment]
Aah, the `type: [string,number,integer,object,array,boolean,null]` syntax is from OpenAPI 3.1. But not valid 3.0. 

Utoipa does not support yet 3.1 spec but the support should be added sometime but not without breaking the 3.0 support. This would need a feature flag to enable 3.1 spec style.

**Comment by jayvdb** [comment]
ping @juhaku .. is this now an acceptable approach?

**Review by juhaku — APPROVED** [review]
Super, I think this will do for now :1st_place_medal: Need to explore the OpenAPI 3.1 support later on. It for sure needs changes for `utoipa-gen` and `utoipa` types itself.

**Pull request merged**
