### PR TITLE
Add support for serde flatten

### PR DESCRIPTION
**Pull request by kw7oe**
Address issue: https://github.com/juhaku/utoipa/issues/120

It's still an early draft and probably missing impl on other applicable areas and test cases. Do let me know if I'm heading towards the right direction.

### CODE REVIEW

**Comment by juhaku** [comment]
Took a quick look and looks promising :+1:  :tada:  Indeed missing at least docs. Also eventually this need to be implemented to the `IntoParams` in `into_params.rs` but there is no serde support at all currently but that can be another story later on.

**Comment by kw7oe** [comment]
Thanks for the review, I'll add another test case where we have nested flatten and also looking into updating the docs as well. For `IntoParams`, I can take a quick look into it and see if I can add the support as well.

**Comment by kw7oe** [comment]
Hey @juhaku I have update the docs _(I could be missing something as well...)_, added some test cases and I think is ready to be review.

For the `IntoParams`, since I have less context on it since I haven't need to use it so far. While I would still like to tackle on this, would you mind to sharing more details to me? For example:
- is the goal to be supporting `param(flatten)`? 
- where should I be adding the test cases if I implemented it? I see a couple of files that might be related to this work like `path_derive*.rs` and `path_parameter_derive*.rs`. Having a pointer would be great hahaha

And I totally understand that you are occupied with personal things, so take all the time you need. Nothing is urgent here. I would just like to contribute some work back to upstream.

**Review by juhaku — APPROVED** [review]
Looks good to me :100:

**Comment by juhaku** [comment]
> is the goal to be supporting param(flatten)?

Yes

> where should I be adding the test cases if I implemented it?

`utoipa-gen/tests/path_derive.rs` Seems like the place.. There already is some IntoParams tests. Essentially the functionality is the same. It `IntoParams` is used to create openapi request parameters from rust structs.

**Comment by juhaku** [comment]
The `IntoParams` implementation can be a separate PR. I can merge this one to master.

**Pull request merged**
