### PR TITLE
fix: tagged enum with flatten fields

### LINKED ISSUE #1206: no method named `property` found for struct `utoipa::openapi::AllOfBuilder` in the current scope
Hello,

While implementing ToSchema on a project, I got the following error:
```
error[E0599]: no method named `property` found for struct `utoipa::openapi::AllOfBuilder` in the current scope
  --> src/main.rs:14:21
   |
14 | #[derive(Serialize, ToSchema)]
   |                     ^^^^^^^^ method not found in `AllOfBuilder`
   |
   = note: this error originates in the derive macro `ToSchema` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I made a small test project to reproduce the issue:
```rust
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Serialize, ToSchema)]
pub struct F {}

#[derive(Serialize, ToSchema)]
#[serde(tag = "test_c")]
pub enum C {
    D,
    E(F)
}

#[derive(Serialize, ToSchema)] // <-- Error happens here
#[serde(tag = "test_a")]
pub enum A {
    B {
        #[serde(flatten)]
        c: C
    }
}

fn main() {}
```

Here is the code generated with cargo expand:

<details>

<summary>Cargo expand</summary>

```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
use serde::Serialize;
use utoipa::ToSchema;
pub struct F {}
#[doc(hidden)]
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _: () = {
    #[allow(unused_extern_crates, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl _serde::Serialize for F {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer,
        {
            let __serde_state = _serde::Serializer::serialize_struct(
                __serializer,
                "F",
                false as usize,
            )?;
            _serde::ser::SerializeStruct::end(__serde_state)
        }
    }
};
impl utoipa::__dev::ComposeSchema for F {
    fn compose(
        mut generics: Vec<utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>>,
    ) -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
        {
            let mut object = utoipa::openapi::ObjectBuilder::new();
            object
        }
            .into()
    }
}
impl utoipa::ToSchema for F {
    fn name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("F")
    }
    fn schemas(
        schemas: &mut Vec<
            (String, utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>),
        >,
    ) {
        schemas.extend([]);
    }
}
#[serde(tag = "test_c")]
pub enum C {
    D,
    E(F),
}
#[doc(hidden)]
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _: () = {
    #[allow(unused_extern_crates, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl _serde::Serialize for C {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer,
        {
            match *self {
                C::D => {
                    let mut __struct = _serde::Serializer::serialize_struct(
                        __serializer,
                        "C",
                        1,
                    )?;
                    _serde::ser::SerializeStruct::serialize_field(
                        &mut __struct,
                        "test_c",
                        "D",
                    )?;
                    _serde::ser::SerializeStruct::end(__struct)
                }
                C::E(ref __field0) => {
                    _serde::__private::ser::serialize_tagged_newtype(
                        __serializer,
                        "C",
                        "E",
                        "test_c",
                        "E",
                        __field0,
                    )
                }
            }
        }
    }
};
impl utoipa::__dev::ComposeSchema for C {
    fn compose(
        mut generics: Vec<utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>>,
    ) -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
        Into::<
            utoipa::openapi::schema::OneOfBuilder,
        >::into(utoipa::openapi::OneOf::with_capacity(2usize))
            .item(
                utoipa::openapi::schema::Object::builder()
                    .property(
                        "test_c",
                        utoipa::openapi::schema::Object::builder()
                            .schema_type(
                                utoipa::openapi::schema::SchemaType::new(
                                    utoipa::openapi::schema::Type::String,
                                ),
                            )
                            .enum_values::<[&str; 1usize], &str>(Some(["D"])),
                    )
                    .required("test_c"),
            )
            .item(
                utoipa::openapi::schema::AllOfBuilder::new()
                    .item(
                        utoipa::openapi::schema::RefBuilder::new()
                            .ref_location_from_schema_name({
                                let res = ::alloc::fmt::format(
                                    format_args!("{0}", <F as utoipa::ToSchema>::name()),
                                );
                                res
                            }),
                    )
                    .item(
                        utoipa::openapi::schema::Object::builder()
                            .property(
                                "test_c",
                                utoipa::openapi::schema::Object::builder()
                                    .schema_type(
                                        utoipa::openapi::schema::SchemaType::new(
                                            utoipa::openapi::schema::Type::String,
                                        ),
                                    )
                                    .enum_values::<[&str; 1usize], &str>(Some(["E"])),
                            )
                            .required("test_c"),
                    ),
            )
            .into()
    }
}
impl utoipa::ToSchema for C {
    fn name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("C")
    }
    fn schemas(
        schemas: &mut Vec<
            (String, utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>),
        >,
    ) {
        schemas
            .extend([
                (
                    String::from({
                        let res = ::alloc::fmt::format(
                            format_args!("{0}", <F as utoipa::ToSchema>::name()),
                        );
                        res
                    }),
                    <F as utoipa::PartialSchema>::schema(),
                ),
            ]);
        <F as utoipa::ToSchema>::schemas(schemas);
    }
}
#[serde(tag = "test_a")]
pub enum A {
    B { #[serde(flatten)] c: C },
}
#[doc(hidden)]
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _: () = {
    #[allow(unused_extern_crates, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl _serde::Serialize for A {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer,
        {
            match *self {
                A::B { ref c } => {
                    let mut __serde_state = _serde::Serializer::serialize_map(
                        __serializer,
                        _serde::__private::None,
                    )?;
                    _serde::ser::SerializeMap::serialize_entry(
                        &mut __serde_state,
                        "test_a",
                        "B",
                    )?;
                    _serde::Serialize::serialize(
                        &c,
                        _serde::__private::ser::FlatMapSerializer(&mut __serde_state),
                    )?;
                    _serde::ser::SerializeMap::end(__serde_state)
                }
            }
        }
    }
};
impl utoipa::__dev::ComposeSchema for A {
    fn compose(
        mut generics: Vec<utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>>,
    ) -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
        Into::<
            utoipa::openapi::schema::OneOfBuilder,
        >::into(utoipa::openapi::OneOf::with_capacity(1usize))
            .item(
                utoipa::openapi::AllOfBuilder::new()
                    .item(
                        utoipa::openapi::schema::RefBuilder::new()
                            .ref_location_from_schema_name({
                                let res = ::alloc::fmt::format(
                                    format_args!("{0}", <C as utoipa::ToSchema>::name()),
                                );
                                res
                            }),
                    )
                    .item({
                        let mut object = utoipa::openapi::ObjectBuilder::new();
                        object
                    })
                    .property(
                        "test_a",
                        utoipa::openapi::schema::Object::builder()
                            .schema_type(
                                utoipa::openapi::schema::SchemaType::new(
                                    utoipa::openapi::schema::Type::String,
                                ),
                            )
                            .enum_values::<[&str; 1usize], &str>(Some(["B"])),
                    )
                    .required("test_a"),
            )
            .into()
    }
}
impl utoipa::ToSchema for A {
    fn name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("A")
    }
    fn schemas(
        schemas: &mut Vec<
            (String, utoipa::openapi::RefOr<utoipa::openapi::schema::Schema>),
        >,
    ) {
        schemas
            .extend([
                (
                    String::from({
                        let res = ::alloc::fmt::format(
                            format_args!("{0}", <C as utoipa::ToSchema>::name()),
                        );
                        res
                    }),
                    <C as utoipa::PartialSchema>::schema(),
                ),
            ]);
        <C as utoipa::ToSchema>::schemas(schemas);
    }
}
fn main() {}
```

</details>

### PR DESCRIPTION
**Pull request by TLDMain**
Closes #1206
This is a quick solution to the problem; the coding style might not align with conventional standards, but I am ready to address any shortcomings.

### CODE REVIEW

**Comment by Obiwan1995** [comment]
Is there any progress on this? We need this PR to be merged.

**Review by juhaku — APPROVED** [review]
Seems good to me, could you add a CHANGLOG entry in `utoipa-gen` for the change. 

Here is example format of what should be added at the very top of the `CHANGELOG.md`
```markdown
## Unreleased

### Changed 

* title (http://PR)
```

> Is there any progress on this? We need this PR to be merged.

Sure, I have been quite busy with life recently.

**Comment by TLDMain** [comment]
@juhaku done

**Review by juhaku — APPROVED** [review]
Super, :100:

**Pull request merged**
