### PR TITLE
Switch to oneOf instead allOf to handle nullable values (#1050)

### PR DESCRIPTION
**Pull request by JMLX42**
fix for #1050

### CODE REVIEW

**Review by juhaku — APPROVED** [review]
Looks great, if you add one line to the CHANGELOG.md of utoipa-gen would be perfect. Add it top of the Unreleased section and add sub title Changed.

**Comment by juhaku** [comment]
Great, seems like you have some automatic format for the md files, Can you revert the automatic format? Now there are bunch of unrelated changes. Though they could be formatted, but better for another PR.

**Comment by JMLX42** [comment]
> Great, seems like you have some automatic format for the md files, Can you revert the automatic format? Now there are bunch of unrelated changes. Though they could be formatted, but better for another PR.
> 
> EDIT: and it should be `utoipa-gen/CHANGELOG.md` 🙂

@juhaku Wow my bad. Done and done!

**Review by juhaku — APPROVED** [review]
Super :tada:

**Pull request merged**
